### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by TylerMS887** [TylerMS887/adwaita.css#3]
Adwaita.CSS is not a complete Libadwaita style. Some elements look like what they are in vanilla HTML. This todo helps with tracking progress.

## Theming and Accessibility

- [x] Dark theme with mostly dark design elements ([pull request](https://github.com/TylerMS887/adwaita.css/pull/2))
- [ ] High contrast support with borders

## Elements

- [x] `body`: Increased padding around HTML content
- [x] `dialog`: Libadwaita dialogues with shadows and rounded corners
- [x] `button`: Libadwaita buttons
- [x] `select`: Libadwaita combo boxes
- [x] `input`: Libadwaita inputs (work in progress)
   - [x] `input="checkbox"`
   - [ ] `input="radio"`
   - [ ] `input="text"` and `input="textbox"`
